"""Add account lockout fields to users table

Revision ID: 20250727220000
Revises: 20250727210000
Create Date: 2025-07-27 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250727220000'
down_revision = '20250727210000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_failed_login', sa.DateTime(timezone=True), nullable=True))
    
    # Add indexes for lockout queries
    op.create_index('idx_users_failed_attempts', 'users', ['failed_login_attempts'], unique=False)
    op.create_index('idx_users_locked_until', 'users', ['locked_until'], unique=False)
    op.create_index('idx_users_last_failed_login', 'users', ['last_failed_login'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_last_failed_login', table_name='users')
    op.drop_index('idx_users_locked_until', table_name='users')
    op.drop_index('idx_users_failed_attempts', table_name='users')
    op.drop_column('users', 'last_failed_login')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###