version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: m-erp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: m_erp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for messaging and caching
  redis:
    image: redis:7-alpine
    container_name: m-erp-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # User Authentication Service
  user-auth-service:
    build: ./services/user-auth-service
    container_name: m-erp-user-auth
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/user_auth_db
      SECRET_KEY: development-secret-key-change-in-production
      ENVIRONMENT: development
      DEBUG: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/user-auth-service:/app
    restart: unless-stopped

  # Company Partner Service
  company-partner-service:
    build: ./services/company-partner-service
    container_name: m-erp-company-partner
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/company_partner_db
      AUTH_SERVICE_URL: http://kong:8000
      SERVICE_KEY: company-partner-service-key
      ENVIRONMENT: development
      DEBUG: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-auth-service:
        condition: service_started
    volumes:
      - ./services/company-partner-service:/app
    restart: unless-stopped

  # Menu Access Service
  menu-access-service:
    build: ./services/menu-access-service
    container_name: m-erp-menu-access
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/menu_access_db
      AUTH_SERVICE_URL: http://user-auth-service:8000
      SERVICE_KEY: menu-access-service-key
      ENVIRONMENT: development
      DEBUG: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-auth-service:
        condition: service_started
    volumes:
      - ./services/menu-access-service:/app
    restart: unless-stopped

  # API Gateway (Kong)
  kong:
    image: kong:3.4
    container_name: m-erp-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "9080:8000"  # Proxy port (main API gateway)
      - "9001:8001"  # Admin API port
    volumes:
      - ./services/api-gateway/kong.yml:/kong/kong.yml:ro
    depends_on:
      - user-auth-service
      - company-partner-service
      - menu-access-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  # UI Service (Vue.js Frontend)
  ui-service:
    build: ./services/ui-service
    container_name: m-erp-ui
    ports:
      - "3000:80"  # Frontend interface
    environment:
      NODE_ENV: production
    depends_on:
      - kong
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data: