#!/usr/bin/env python3
"""Test JWT token decoding."""

import jwt
import json
import base64

# The JWT token
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJwZXJtaXNzaW9ucyI6WyJtYW5hZ2VfdXNlcnMiLCJtYW5hZ2Vfcm9sZXMiLCJtYW5hZ2Vfc3lzdGVtIiwidmlld19hdWRpdF9sb2dzIiwibWFuYWdlX2NvbXBhbmllcyIsIm1hbmFnZV9wYXJ0bmVycyIsIm1hbmFnZV9jdXJyZW5jaWVzIiwiYWNjZXNzX2FkbWluX2Rhc2hib2FyZCIsImNvbXBhbmllcy52aWV3IiwiY29tcGFuaWVzLmNyZWF0ZSIsImNvbXBhbmllcy51cGRhdGUiLCJjb21wYW5pZXMuZGVsZXRlIiwicGFydG5lcnMudmlldyIsInBhcnRuZXJzLmNyZWF0ZSIsInBhcnRuZXJzLnVwZGF0ZSIsInBhcnRuZXJzLmRlbGV0ZSIsInVzZXJzLnZpZXciLCJ1c2Vycy5jcmVhdGUiLCJ1c2Vycy51cGRhdGUiLCJ1c2Vycy5kZWxldGUiLCJpbnZlbnRvcnkuYWNjZXNzIiwiaW52ZW50b3J5Lm1hbmFnZSIsInNhbGVzLmFjY2VzcyIsInNhbGVzLm1hbmFnZSIsIm1lbnUudmlldyIsIm1lbnUuYWRtaW4iLCJhZG1pbi5hY2Nlc3MiLCJjdXN